language: node_js
node_js:
  - "8"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y lftp
  - npm install -g gatsby-cli@1.0.9
install:
  - yarn
script:
  - gatsby build
after_success: "lftp -c 'open -u ${USER_NAME},${PASSWORD} ftp://${SERVER_ADDRESS}; mirror -R aberkow/gatsby-blog/public/ /public_html/'"
#after_success: "lftp ftp://${USER_NAME}:${PASSWORD}@${SERVER_ADDRESS}/public_html/ -e 'mirror -R'"
cache:
  directories:
    - "node_modules"